### ISSUE TITLE
[Suggestion:UX] Allow user to store a working size option.

### ISSUE THREAD

**Issue by seilfx** [haxi0/TrollLock-Reborn#3]
Add an option to set a default size instead of having to pick it every time you reset the lock icon. Alternatively, detect which file works best for the device (e.g. map the correct sizes to their devices in a JSON file).

**Comment by haxi0** [comment]
ios wont accept it then, it only has a default size for all devices, as far as i think. but i dont think you can make it bigger

**Comment by seilfx** [comment]
There seems to be a misunderstanding. What I mean is an option to store the correct size option from this menu:
![FD9DDEF6-6167-4D9C-910C-19B1EA601679](https://user-images.githubusercontent.com/99132199/209537221-8fbe2df4-1e1c-4580-b4e0-53f8cd30cc77.jpeg)
