### ISSUE TITLE
respring not working

### ISSUE THREAD

**Issue by binnichtaktiv** [haxi0/TrollLock-Reborn#7]
Hi
I tried to respring like you did but its not working. Whats wrong?

https://user-images.githubusercontent.com/96953964/209812658-05b97a49-8132-4631-a27d-8f8c2ab43050.mp4

**Comment by haxi0** [comment]
press backspace while dragging

**Comment by binnichtaktiv** [comment]
> press backspace while dragging

Still not working. I’m on iOS 16.1.2 iPhone 11

https://user-images.githubusercontent.com/96953964/209870045-718d72e8-bb07-40d2-9c97-1da60e4a10c3.MOV
